config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /pl|en/ do
    devise_for :users

    get   '/orders/prepare',  to: 'orders#prepare'
    get   '/orders/send_message', to: 'orders#prepare'
    post  '/orders/send_message', to: 'orders#send_message'

    resources :cart, only: :index
    post  '/cart_add',     to: 'cart#cart_add_to'
    post  '/cart_remove',  to: 'cart#cart_remove_from'
    get   '/cart_empty',   to: 'cart#cart_empty'

    get '/search', to: 'products#index'
    resources :products do
      resources :volumes
    end
  
    get '/kontakt', to: 'kontakt#kontakt', as: :kontakt

    scope '/aerozole' do
      get '/nasze-aerozole',    to: 'aerozole#nasze_aerozole', as: :nasze_aerozole
      get '/aerozole-w-zyciu',  to: 'aerozole#aerozole_w_zyciu', as: :aerozole_w_zyciu
      get '/proces-produkcji',  to: 'aerozole#proces_produkcji', as: :proces_produkcji
    end

    scope '/firma' do
      get '/o-nas',     to: 'firma#o_nas', as: :o_nas
      get '/gwarancja', to: 'firma#gwarancja', as: :gwarancja
      get '/ekologia',  to: 'firma#ekologia', as: :ekologia
    end

    get '/', to: "firma#o_nas"

  end

  root to: 'firma#o_nas', locale: 'pl'

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  layout 'application_cart'

  def index
    cookies[:koszyk] = JSON.generate({}) if cookies[:koszyk].nil?
    @koszyk = KoszykService.new(koszyk_hash: JSON.parse(cookies[:koszyk]))

    @volumes = Volume.where(id: @koszyk.klucze)
  end



  def cart_add_to
    cookies[:koszyk] = JSON.generate({}) if cookies[:koszyk].nil?
    @koszyk = KoszykService.new(koszyk_hash: JSON.parse(cookies[:koszyk]))

    ilosc = params[:ilosc].to_i
    ilosc = 1 if ilosc <= 0

    if @koszyk.zawartosc_koszyka.include?(params[:wariant])
      @koszyk.dodaj_do_koszyka(merge_hash: { params[:wariant] => (ilosc + @koszyk.ile_sztuk(wariant: params[:wariant])) })
    else
      @koszyk.dodaj_do_koszyka(merge_hash: { params[:wariant] => ilosc })
    end

    cookies[:koszyk] = JSON.generate(@koszyk.zawartosc_koszyka)
  end



  def cart_remove_from
    @koszyk = KoszykService.new(koszyk_hash: JSON.parse(cookies[:koszyk]))
    
    @koszyk.usun_z_koszyka(wariant: params[:wariant])
    
    cookies[:koszyk] = JSON.generate(@koszyk.zawartosc_koszyka)

    @volumes = Volume.where(id: @koszyk.klucze)
  end



  def cart_empty
    @koszyk = KoszykService.new(koszyk_hash: JSON.parse(cookies[:koszyk]))
    
    @koszyk.oproznij_koszyk

    cookies[:koszyk] = JSON.generate(@koszyk.zawartosc_koszyka)

    @volumes = Volume.where(id: @koszyk.klucze)
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_zawartosc_koszyka.en.html.erb
<% @suma = 0 %>
<% @waluty = [] %>

<div class="table-responsive">
  <table class="table border">
    <thead>
      <tr>
        <th scope="col">Symbol</th>
        <th scope="col">Capacity</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Worth</th>
        <th scope="col">-</th>
      </tr>
    </thead>
    <tbody>

      <% @volumes.each do |volume| %>
        
        <% @produkt = Product.where(id: volume.product_id).take %>
        <% @ilosc = @koszyk.ile_sztuk(wariant: volume.id.to_s).to_i %>

        <tr>
          <td><%= link_to @produkt.kod, product_path(params[:locale], @produkt.id) %></td>
          <td><%= volume.pojemnosc %></td>
          <td><%= @ilosc %></td>
          <td><%= number_to_currency(volume.cena, unit: volume.waluta + " ") %></td>
          <td><%= number_to_currency(@ilosc * volume.cena, unit: volume.waluta + " ") %></td>
          
          <td>
            <%= form_with(url: "/#{params[:locale]}/cart_remove", method: :post) do %>
              <%= hidden_field_tag(:wariant, volume.id) %>
              <%= submit_tag("Delete", data: { confirm: 'Are you sure you want to remove the product from the cart?' }, class: 'btn btn-sm btn-danger') %>
            <% end %>
          </td>

        </tr>

        <% @suma += (@ilosc * volume.cena) %>
        <% @waluty << volume.waluta %>
        <% @waluta = volume.waluta %>

      <% end %>

    </tbody>
  </table>
</div>



<% if @waluty.uniq.size > 1 %>
  There are products in different currencies in the cart!
<% else %>
  <% if @suma > 0 %>
    <p>
      <%= form_with(url: "/#{params[:locale]}/cart_empty", method: :get) do %>
        <%= submit_tag("Empty cart", data: { confirm: 'Are you sure you want to empty the cart?'}, class: 'btn btn-danger') %>
      <% end %>
    </p>
  <% end %>


  <% if @suma > 0 %>
    <hr>
    
    <p>TOTAL: <%= number_to_currency(@suma, unit: @waluta + " ") %></p>

    <p><%= link_to 'Add address details', orders_prepare_path, class: 'btn btn-dark' %></p>
  <% end %>
<% end %>

app/views/cart/_zawartosc_koszyka.html.erb
<% @suma = 0 %>
<% @waluty = [] %>

<div class="table-responsive">
  <table class="table border">
    <thead>
      <tr>
        <th scope="col">Kod</th>
        <th scope="col">Pojemność</th>
        <th scope="col">Ilość</th>
        <th scope="col">Cena</th>
        <th scope="col">Wartość</th>
        <th scope="col">-</th>
      </tr>
    </thead>
    <tbody>

      <% @volumes.each do |volume| %>
        
        <% @produkt = Product.where(id: volume.product_id).take %>
        <% @ilosc = @koszyk.ile_sztuk(wariant: volume.id.to_s).to_i %>

        <tr>
          <td><%= link_to @produkt.kod, product_path(params[:locale], @produkt.id) %></td>
          <td><%= volume.pojemnosc %></td>
          <td><%= @ilosc %></td>
          <td><%= number_to_currency(volume.cena, unit: volume.waluta + " ") %></td>
          <td><%= number_to_currency(@ilosc * volume.cena, unit: volume.waluta + " ") %></td>
          
          <td>
            <%= form_with(url: "/#{params[:locale]}/cart_remove", method: :post) do %>
              <%= hidden_field_tag(:wariant, volume.id) %>
              <%= submit_tag("Usuń", data: { confirm: 'Czy na pewno usunąć produkt z koszyka?' }, class: 'btn btn-sm btn-danger') %>
            <% end %>
          </td>

        </tr>

        <% @suma += (@ilosc * volume.cena) %>
        <% @waluty << volume.waluta %>
        <% @waluta = volume.waluta %>

      <% end %>

    </tbody>
  </table>
</div>



<% if @waluty.uniq.size > 1 %>
  W koszyku znajdują się produkty w różnych walutach!
<% else %>
  <% if @suma > 0 %>
    <p>
      <%= form_with(url: "/#{params[:locale]}/cart_empty", method: :get) do %>
        <%= submit_tag("Opróżnij koszyk", data: { confirm: 'Czy na pewno opróżnić koszyk?'}, class: 'btn btn-danger') %>
      <% end %>
    </p>
  <% end %>


  <% if @suma > 0 %>
    <hr>
    
    <p>SUMA: <%= number_to_currency(@suma, unit: @waluta + " ") %></p>

    <p><%= link_to 'Dodaj dane adresowe', orders_prepare_path, class: 'btn btn-dark' %></p>
  <% end %>
<% end %>

app/views/cart/cart_add_to.js.erb
var elems = document.getElementsByClassName('koszyk-slot');

for (var i = 0; i <= elems.length - 1; i++) {
  elems[i].innerHTML = "<%= j(render partial: 'layouts/koszyk') %>";
}

app/views/cart/cart_empty.js.erb
var elem = document.getElementById('zawartosc-koszyka-slot');
elem.innerHTML = "<%= j render partial: 'cart/zawartosc_koszyka' %>";


var elems = document.getElementsByClassName('koszyk-slot');

for (var i = 0; i <= elems.length - 1; i++) {
  elems[i].innerHTML = "<%= j(render partial: 'layouts/koszyk') %>";
}

app/views/cart/cart_remove_from.js.erb
var elem = document.getElementById('zawartosc-koszyka-slot');
elem.innerHTML = "<%= j render partial: 'cart/zawartosc_koszyka' %>";


var elems = document.getElementsByClassName('koszyk-slot');

for (var i = 0; i <= elems.length - 1; i++) {
  elems[i].innerHTML = "<%= j(render partial: 'layouts/koszyk') %>";
}

app/views/cart/index.en.html.erb
<% content_for :title do %>
  <title>Cart</title>
<% end %>



<h2>Cart items:</h2>

<div id="zawartosc-koszyka-slot">
  <%= render 'cart/zawartosc_koszyka' %>
</div>

app/views/cart/index.html.erb
<% content_for :title do %>
  <title>Koszyk</title>
<% end %>



<h2>Zawartość koszyka:</h2>

<div id="zawartosc-koszyka-slot">
  <%= render 'cart/zawartosc_koszyka' %>
</div>