config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /pl|en/ do
    devise_for :users

    get   '/orders/prepare',  to: 'orders#prepare'
    get   '/orders/send_message', to: 'orders#prepare'
    post  '/orders/send_message', to: 'orders#send_message'

    resources :cart, only: :index
    post  '/cart_add',     to: 'cart#cart_add_to'
    post  '/cart_remove',  to: 'cart#cart_remove_from'
    get   '/cart_empty',   to: 'cart#cart_empty'

    get '/search', to: 'products#index'
    resources :products do
      resources :volumes
    end
  
    get '/kontakt', to: 'kontakt#kontakt', as: :kontakt

    scope '/aerozole' do
      get '/nasze-aerozole',    to: 'aerozole#nasze_aerozole', as: :nasze_aerozole
      get '/aerozole-w-zyciu',  to: 'aerozole#aerozole_w_zyciu', as: :aerozole_w_zyciu
      get '/proces-produkcji',  to: 'aerozole#proces_produkcji', as: :proces_produkcji
    end

    scope '/firma' do
      get '/o-nas',     to: 'firma#o_nas', as: :o_nas
      get '/gwarancja', to: 'firma#gwarancja', as: :gwarancja
      get '/ekologia',  to: 'firma#ekologia', as: :ekologia
    end

    get '/', to: "firma#o_nas"

  end

  root to: 'firma#o_nas', locale: 'pl'

end

app/models/volume.rb
# == Schema Information
#
# Table name: volumes
#
#  id         :integer          not null, primary key
#  product_id :integer          not null
#  pojemnosc  :string
#  cena       :decimal(10, 2)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  waluta     :string
#
class Volume < ApplicationRecord
  belongs_to :product

  validates :pojemnosc, presence: true
  validates :cena, presence: true
  validates :waluta, presence: true
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  
  def new
    @product = Product.find(params[:product_id])
    @volumes = @product.volumes.all
    @volume = @product.volumes.new
  end

  def edit
    @product = Product.find(params[:product_id])
    @volumes = @product.volumes.all
    @volume = @product.volumes.find(params[:id])
  end

  def create
    @product = Product.find(params[:product_id])
    @volume = @product.volumes.new(volume_params)

    if @volume.save
      redirect_to product_path(params[:locale], @product.id)
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:product_id])
    @volume = @product.volumes.find(params[:id])

    if @volume.update(volume_params)
      redirect_to product_path(params[:locale], @product.id)
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @volume = @product.volumes.find(params[:id])

    @volume.destroy
    redirect_to product_path(params[:locale], @product.id)
  end

  private

  def volume_params
    params.require(:volume).permit(:pojemnosc, :cena, :waluta)
  end
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/volumes/edit.html.erb
<% content_for :title do %>
  <title>Edytuj pojemność i cenę</title>
<% end %>

<% content_for :metatag_robots do %>
  <meta name="robots" content="noindex nofollow">
<% end %>



<h1><%= @product.kod %></h1>

<p>Aktualne pojemności i ceny:</p>

<p>
  <table class="table border">
    <thead>
      <tr>
        <th scope="col">Pojemność</th>
        <th scope="col">Cena</th>
        <th scope="col">Waluta</th>
      </tr>
    </thead>
    <tbody>
      <% @volumes.each do |volume| %>
        <tr>
            <td><%= volume.pojemnosc %></td>
            <td><%= volume.cena %></td>
            <td><%= volume.waluta %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<p>Edytuj pojemność i cenę:</p>

<p>
  <%= form_with model: [@product, @product.volumes.build], url: product_volume_path(params[:locale], @product), method: :patch do |form| %>
    <%= form.label 'Pojemność:' %>
    <%= form.text_field :pojemnosc, value: "#{@volume.pojemnosc}", class: 'form-control' %>
    <br>
    <%= form.label 'Cena:' %>
    <%= form.text_field :cena, value: "#{@volume.cena}", class: 'form-control' %>
    <br>
    <%= form.label 'Waluta:' %>
    <%= form.text_field :waluta, value: "#{@volume.waluta}", class: 'form-control' %>
    <br>
    <%= form.submit 'Zaktualizuj', class: 'btn btn-secondary' %>
  <% end %>
</p>

app/views/volumes/new.html.erb
<% content_for :title do %>
  <title>Nowa pojemność i cena</title>
<% end %>

<% content_for :metatag_robots do %>
  <meta name="robots" content="noindex nofollow">
<% end %>



<h1><%= @product.kod %></h1>

<p>Aktualne pojemności i ceny:</p>

<p>
  <table class="table border">
    <thead>
      <tr>
        <th scope="col">Pojemność</th>
        <th scope="col">Cena</th>
        <th scope="col">Waluta</th>
      </tr>
    </thead>
    <tbody>
      <% @volumes.each do |volume| %>
        <tr>
            <td><%= volume.pojemnosc %></td>
            <td><%= volume.cena %></td>
            <td><%= volume.waluta %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<p>Nowa pojemność i cena:</p>

<p>
  <%= form_with model: [@product, @product.volumes.build], url: product_volumes_path(params[:locale], @product) do |form| %>
    <%= form.label 'Pojemność:' %>
    <%= form.text_field :pojemnosc, class: 'form-control' %>
    <br>
    <%= form.label 'Cena:' %>
    <%= form.text_field :cena, class: 'form-control' %>
    <br>
    <%= form.label 'Waluta:' %>
    <%= form.text_field :waluta, class: 'form-control' %>
    <br>
    <%= form.submit 'Dodaj', class: 'btn btn-secondary' %>
  <% end %>
</p>