config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /pl|en/ do
    devise_for :users

    get   '/orders/prepare',  to: 'orders#prepare'
    get   '/orders/send_message', to: 'orders#prepare'
    post  '/orders/send_message', to: 'orders#send_message'

    resources :cart, only: :index
    post  '/cart_add',     to: 'cart#cart_add_to'
    post  '/cart_remove',  to: 'cart#cart_remove_from'
    get   '/cart_empty',   to: 'cart#cart_empty'

    get '/search', to: 'products#index'
    resources :products do
      resources :volumes
    end
  
    get '/kontakt', to: 'kontakt#kontakt', as: :kontakt

    scope '/aerozole' do
      get '/nasze-aerozole',    to: 'aerozole#nasze_aerozole', as: :nasze_aerozole
      get '/aerozole-w-zyciu',  to: 'aerozole#aerozole_w_zyciu', as: :aerozole_w_zyciu
      get '/proces-produkcji',  to: 'aerozole#proces_produkcji', as: :proces_produkcji
    end

    scope '/firma' do
      get '/o-nas',     to: 'firma#o_nas', as: :o_nas
      get '/gwarancja', to: 'firma#gwarancja', as: :gwarancja
      get '/ekologia',  to: 'firma#ekologia', as: :ekologia
    end

    get '/', to: "firma#o_nas"

  end

  root to: 'firma#o_nas', locale: 'pl'

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
    @filter = params[:filter]
    page = params[:page]
    per = 6

    if params[:search_kod]
      search_kod = '%' + params[:search_kod] + '%'
      @products = ProductsSearchService.call(locale: params[:locale], search_kod: search_kod, page: page, per: per)
    else
      @products = FilterRouteService.call(@filter, page, per)
    end
  end

  def show
    @product = Product.find(params[:id])
    @volumes = @product.volumes.all.order(pojemnosc: :desc)
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_path(params[:locale], @product)
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to product_path(params[:locale], @product)
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])

    @product.destroy
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:kod, :tytul, :poziom, :kategoria, :ekstra_geste, :geste, :rzadkie, :uniwersalne, :z_ptfe, :z_mos2, :z_grafitem, :biale, :do_lozysk, :do_bram, :do_dzwigow, :do_lancuchow, :do_gumy, :do_rowerow, :do_zamkow, :grafitowo_molibdenowe, :oleje_precyzyjne_lekkie, :dla_rolnictwa_i_lesnictwa, :ochrona_przylaczy, :kontakt_spray, :super_izolator, :zmywacz, :olej_elektroserwisowy, :pasty_miedziane, :ekstra_geste_miedziane, :pasty_ceramiczne, :ekstra_geste_ceramiczne, :pasty_aluminiowe, :plyny_do_ciecia, :oleje_do_gwintowania, :pasty_do_gwintowania, :odtluszczacz_maszynowy, :zmywacz_serwisowy, :zmywacz_smarujacy, :zmywacz_konserwujacy, :olej_ochronny, :wosk_ochronny, :pasta_ochronna, :pasta_do_baterii, :ekstra_gesta_pasta_do_baterii, :wapniowe, :smar_plynny, :smar_polsuchy, :polsuche_srodki_smarne, :oleje_wysokoczepne, :smary_pelzajace, :plyn_do_oringu, :pasta_do_oringu, :ekstra_gesta_pasta_do_oringu, :spraye_rowerowe, :zmywacze_rowerowe, :litowe, :do_wysiegnikow_alu, :miniatura, :opis_krotki, :opis_dlugi, :tytul_en, :opis_krotki_en, :opis_dlugi_en, :tytul_de, :opis_krotki_de, :opis_dlugi_de, :tytul_se, :opis_krotki_se, :opis_dlugi_se, :tytul_ru, :opis_krotki_ru, :opis_dlugi_ru)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  
  def volumes_only(product:)
    Volume.where(product_id: product.id).map { |volume| volume.pojemnosc }.uniq.sort.reverse.join(', ')
  end

  def nazwa_kategorii(filter:, locale:)
    nazwy = {
      'pl' => {
        'wszystkie' => 'Wszystkie produkty',

        'smary' => 'Smary',

        'smary_ekstra_geste' => 'Smary ekstra gęste',
        'smary_ekstra_geste_uniwersalne' => 'Smary ekstra gęste uniwersalne',
        'smary_ekstra_geste_z_ptfe' => 'Smary ekstra gęste z ptfe',
        'smary_ekstra_geste_z_ptfe_litowe' => 'Smary ekstra gęste z ptfe litowe',
        'smary_ekstra_geste_z_mos2' => 'Smary ekstra gęste z mos2',
        'smary_ekstra_geste_z_grafitem' => 'Smary ekstra gęste z grafitem',
        'smary_ekstra_geste_biale' => 'Smary ekstra gęste białe',
        'smary_ekstra_geste_biale_wapniowe' => 'Smary ekstra gęste białe wapniowe',
        'smary_ekstra_geste_biale_z_ptfe' => 'Smary ekstra gęste białe z ptfe',

        'smary_geste' => 'Smary gęste',
        'smary_geste_uniwersalne' => 'Smary gęste uniwersalne',
        'smary_geste_z_ptfe' => 'Smary gęste z ptfe',
        'smary_geste_z_ptfe_litowe' => 'Smary gęste z ptfe litowe',
        'smary_geste_z_mos2' => 'Smary gęste z mos2',
        'smary_geste_z_grafitem' => 'Smary gęste z grafitem',
        'smary_geste_biale' => 'Smary gęste białe',
        'smary_geste_biale_wapniowe' => 'Smary gęste białe wapniowe',
        'smary_geste_biale_z_ptfe' => 'Smary gęste białe z ptfe',

        'smary_rzadkie' => 'Smary rzadkie',
        'smary_rzadkie_uniwersalne' => 'Smary rzadkie uniwersalne',
        'smary_rzadkie_z_ptfe' => 'Smary rzadkie z ptfe',
        'smary_rzadkie_z_ptfe_litowe' => 'Smary rzadkie z ptfe litowe',
        'smary_rzadkie_z_mos2' => 'Smary rzadkie z mos2',
        'smary_rzadkie_z_grafitem' => 'Smary rzadkie z grafitem',
        'smary_rzadkie_biale' => 'Smary rzadkie białe',
        'smary_rzadkie_biale_wapniowe' => 'Smary rzadkie białe wapniowe',
        'smary_rzadkie_biale_z_ptfe' => 'Smary rzadkie białe z ptfe',

        'smary_uniwersalne' => 'Smary uniwersalne',
        'smary_uniwersalne_ekstra_geste' => 'Smary uniwersalne ekstra gęste',
        'smary_uniwersalne_geste' => 'Smary uniwersalne gęste',
        'smary_uniwersalne_rzadkie' => 'Smary uniwersalne rzadkie',

        'smary_z_ptfe' => 'Smary z ptfe',
        'smary_z_ptfe_ekstra_geste' => 'Smary z ptfe ekstra gęste',
        'smary_z_ptfe_geste' => 'Smary z ptfe gęste',
        'smary_z_ptfe_rzadkie' => 'Smary z ptfe rzadkie',

        'smary_z_mos2' => 'Smary z mos2',
        'smary_z_mos2_ekstra_geste' => 'Smary z mos2 ekstra gęste',
        'smary_z_mos2_geste' => 'Smary z mos2 gęste',
        'smary_z_mos2_rzadkie' => 'Smary z mos2 rzadkie',

        'smary_z_grafitem' => 'Smary z grafitem',
        'smary_z_grafitem_ekstra_geste' => 'Smary z grafitem ekstra gęste',
        'smary_z_grafitem_geste' => 'Smary z grafitem gęste',
        'smary_z_grafitem_rzadkie' => 'Smary z grafitem rzadkie',

        'smary_biale' => 'Smary białe',
        'smary_biale_wapniowe' => 'Smary białe wapniowe',
        'smary_biale_wapniowe_ekstra_geste' => 'Smary białe wapniowe ekstra gęste',
        'smary_biale_wapniowe_geste' => 'Smary białe wapniowe gęste',
        'smary_biale_wapniowe_rzadkie' => 'Smary białe wapniowe rzadkie',
        'smary_biale_z_ptfe' => 'Smary białe z ptfe',
        'smary_biale_z_ptfe_ekstra_geste' => 'Smary białe z ptfe ekstra gęste',
        'smary_biale_z_ptfe_geste' => 'Smary białe z ptfe gęste',
        'smary_biale_z_ptfe_rzadkie' => 'Smary białe z ptfe rzadkie',

        'dedykowane' => 'Dedykowane',

        'dedykowane_do_lozysk' => 'Dedykowane do łożysk',
        'dedykowane_do_lozysk_uniwersalne' => 'Dedykowane do łożysk uniwersalne',
        'dedykowane_do_lozysk_z_ptfe' => 'Dedykowane do łożysk z ptfe',
        'dedykowane_do_lozysk_z_mos2' => 'Dedykowane_do_łożysk z mos2',

        'dedykowane_do_bram' => 'Dedykowane do bram',
        'dedykowane_do_bram_uniwersalne' => 'Dedykowane do bram uniwersalne',
        'dedykowane_do_bram_z_ptfe' => 'Dedykowane do bram z ptfe',
        'dedykowane_do_bram_z_mos2' => 'Dedykowane do bram z mos2',
        
        'dedykowane_do_dzwigow' => 'Dedykowane do dźwigów',
        'dedykowane_do_dzwigow_smar_plynny' => 'Dedykowane do dźwigów smar płynny',
        'dedykowane_do_dzwigow_smar_plynny_uniwersalne' => 'Dedykowane do dźwigów smar płynny uniwersalne',
        'dedykowane_do_dzwigow_smar_polsuchy' => 'Dedykowane do dźwigów smar półsuchy',
        'dedykowane_do_dzwigow_smar_polsuchy_z_ptfe' => 'Dedykowane do dźwigów smar półsuchy z ptfe',
        'dedykowane_do_dzwigow_smar_polsuchy_z_mos2' => 'Dedykowane do dźwigów smar półsuchy z mos2',
        'dedykowane_do_dzwigow_smar_polsuchy_z_grafitem' => 'Dedykowane do dźwigów smar półsuchy z grafitem',
        'dedykowane_do_dzwigow_smar_polsuchy_do_wysiegnikow_alu' => 'Dedykowane do dźwigów smar półsuchy do wysięgników alu',

        'dedykowane_do_lancuchow' => 'Dedykowane do łancuchów',
        'dedykowane_do_lancuchow_polsuche_srodki_smarne' => 'Dedykowane do łańcuchów półsuche środki smarne',
        'dedykowane_do_lancuchow_polsuche_srodki_smarne_uniwersalne' => 'Dedykowane do łańcuchów półsuche środki smarne uniwersalne',
        'dedykowane_do_lancuchow_polsuche_srodki_smarne_z_ptfe' => 'Dedykowane do łańcuchów półsuche środki smarne z ptfe',
        'dedykowane_do_lancuchow_polsuche_srodki_smarne_z_mos2' => 'Dedykowane do łańcuchów półsuche środki smarne z mos2',
        'dedykowane_do_lancuchow_polsuche_srodki_smarne_z_grafitem' => 'Dedykowane do łańcuchów półsuche środki smarne z grafitem',
        'dedykowane_do_lancuchow_oleje_wysokoczepne' => 'Dedykowane do łańcuchów oleje wysokoczepne',
        'dedykowane_do_lancuchow_oleje_wysokoczepne_uniwersalne' => 'Dedykowane do łańcuchów oleje wysokoczepne uniwersalne',
        'dedykowane_do_lancuchow_oleje_wysokoczepne_z_ptfe' => 'Dedykowane do łańcuchów oleje wysokoczepne z ptfe',
        'dedykowane_do_lancuchow_oleje_wysokoczepne_z_mos2' => 'Dedykowane do łańcuchów oleje wysokoczepne z mos2',
        'dedykowane_do_lancuchow_oleje_wysokoczepne_z_grafitem' => 'Dedykowane do łańcuchów oleje wysokoczepne z grafitem',
        'dedykowane_do_lancuchow_smary_pelzajace' => 'Dedykowane do łańcuchów smary pełzające',
        'dedykowane_do_lancuchow_smary_pelzajace_uniwersalne' => 'Dedykowane do łańcuchów smary pełzające uniwersalne',
        'dedykowane_do_lancuchow_smary_pelzajace_z_ptfe' => 'Dedykowane do łańcuchów smary pełzające z ptfe',
        'dedykowane_do_lancuchow_smary_pelzajace_z_mos2' => 'Dedykowane do łańcuchów smary pełzające z mos2',
        'dedykowane_do_lancuchow_smary_pelzajace_z_grafitem' => 'Dedykowane do łańcuchów smary pełzające z grafitem',

        'dedykowane_do_gumy' => 'Dedykowane do gumy',
        'dedykowane_do_gumy_plyn_do_oringu' => 'Dedykowane do gumy płyn do oringu',
        'dedykowane_do_gumy_pasta_do_oringu' => 'Dedykowane do gumy pasta do oringu',
        'dedykowane_do_gumy_ekstra_gesta_pasta_do_oringu' => 'Dedykowane do gumy ekstra gęsta pasta do oringu',

        'dedykowane_do_rowerow' => 'Dedykowane do rowerów',
        'dedykowane_do_rowerow_spraye_rowerowe' => 'Dedykowane do rowerów spraye rowerowe',
        'dedykowane_do_rowerow_zmywacze_rowerowe' => 'Dedykowane do rowerów zmywacze rowerowe',

        'dedykowane_do_zamkow' => 'Dedykowane do zamków',
        'dedykowane_do_zamkow_uniwersalne' => 'Dedykowane do zamków uniwersalne',
        'dedykowane_do_zamkow_z_ptfe' => 'Dedykowane do zamków z ptfe',

        'odrdzewiacze' => 'Odrdzewiacze',

        'odrdzewiacze_uniwersalne' => 'Odrdzewiacze uniwersalne',
        'odrdzewiacze_z_ptfe' => 'Odrdzewiacze z ptfe',
        'odrdzewiacze_z_mos2' => 'Odrdzewiacze z mos2',
        'odrdzewiacze_z_grafitem' => 'Odrdzewiacze z grafitem',
        'odrdzewiacze_grafitowo_molibdenowe' => 'Odrdzewiacze grafitowo molibdenowe',

        'multispraye' => 'Multispraye',

        'multispraye_uniwersalne' => 'Multispraye uniwersalne',
        'multispraye_z_ptfe' => 'Multispraye z ptfe',
        'multispraye_z_mos2' => 'Multispraye z mos2',
        'multispraye_z_grafitem' => 'Multispraye z grafitem',

        'oleje' => 'Oleje',

        'oleje_oleje_precyzyjne_lekkie' => 'Oleje oleje precyzyjne lekkie',
        'oleje_uniwersalne' => 'Oleje uniwersalne',
        'oleje_z_ptfe' => 'Oleje z ptfe',
        'oleje_z_mos2' => 'Oleje z mos2',
        'oleje_z_grafitem' => 'Oleje z grafitem',
        'oleje_dla_rolnictwa_i_lesnictwa' => 'Oleje dla rolnictwa i leśnictwa',

        'elektryka_i_mechanika' => 'Elektryka i mechanika',

        'elektryka_i_mechanika_ochrona_przylaczy' => 'Elektryka i mechanika ochrona przyłączy',
        'elektryka_i_mechanika_kontakt_spray' => 'Elektryka i mechanika kontakt spray',
        'elektryka_i_mechanika_super_izolator' => 'Elektryka i mechanika super izolator',
        'elektryka_i_mechanika_zmywacz' => 'Elektryka i mechanika zmywacz',
        'elektryka_i_mechanika_olej_elektroserwisowy' => 'Elektryka i mechanika olej elektroserwisowy',

        'pasty_montazowe_ochronne' => 'Pasty montażowe ochronne',

        'pasty_montazowe_ochronne_pasty_miedziane' => 'Pasty montażowe ochronne pasty miedziane',
        'pasty_montazowe_ochronne_ekstra_geste_miedziane' => 'Pasty montażowe ochronne ekstra gęste miedziane',
        'pasty_montazowe_ochronne_pasty_ceramiczne' => 'Pasty montażowe ochronne pasty ceramiczne',
        'pasty_montazowe_ochronne_ekstra_geste_ceramiczne' => 'Pasty montażowe ochronne ekstra gęste ceramiczne',
        'pasty_montazowe_ochronne_pasty_aluminiowe' => 'Pasty montażowe ochronne pasty aluminiowe',

        'obrobka_metali' => 'Obróbka metali',

        'obrobka_metali_plyny_do_ciecia' => 'Obróbka metali płyny do cięcia',
        'obrobka_metali_oleje_do_gwintowania' => 'Obróbka metali oleje do gwintowania',

app/views/products/_przypomnienie.en.html.erb
<div class="center">
  <% if @product.poziom < 6 %>
    <h3><%= @product.tytul_en %></h3>
    <br>
    <h3><strong>Remember! Level <%= @product.poziom %> is not the level SEX (6)!</strong></h3>
  <% else %>
    <h3><strong>Invest once!</strong></h3>
  <% end %>
</div>

app/views/products/_przypomnienie.html.erb
<div class="center">
  <% if @product.poziom < 6 %>
    <h3><%= @product.tytul %></h3>
    <br>
    <h3><strong>Pamiętaj! Poziom <%= @product.poziom %> to nie poziom SEX (6)!</strong></h3>
  <% else %>
    <h3><strong>Zainwestuj raz!</strong></h3>
  <% end %>
</div>

app/views/products/edit.html.erb
<% content_for :title do %>
  <title>Edytuj produkt</title>
<% end %>

<% content_for :metatag_robots do %>
  <meta name="robots" content="noindex nofollow">
<% end %>



<h1>Edytuj produkt</h1>

<br>

<%= form_with model: @product, url: product_path(locale: params[:locale]) do |form| %>

  <%= render 'form_new_and_edit', form: form, product: @product %>

  <br>

  <%= form.submit 'Zaktualizuj produkt', method: :patch, class: 'btn btn-secondary' %>

<% end %>

app/views/products/index.en.html.erb
<% content_for :title do %>
  <title>Products</title>
<% end %>



<% if @filter %>
  <h2><strong><%= nazwa_kategorii(filter: @filter, locale: params[:locale]) %></strong></h2>
<% end %>



<%= form_with(url: "/#{params[:locale]}/search", method: "get", local: true) do %>
  
  <div class="input-group mb-3">
    <%= text_field_tag(:search_kod, '', class: 'form-control') %>
    <div class="input-group-append">
      <%= submit_tag("Search", class: 'btn btn-outline-secondary') %>
    </div>
  </div>

<% end %>



<% @products.each do |product| %>

  <div class="container py-3 mb-3 border shadow-sm">
    <div class="row">

      <div class="col-12 col-md-3">
        <%= link_to(product_path(params[:locale], product.id), class: "thumbnail") do %>
          <%= image_tag(url_for(product.miniatura), width: '100', height: '150', class: 'ml-4 mb-4') %>
        <% end %>
      </div>

      <div class="col-12 col-md-9">
        <h4>
          <strong><%= link_to product.kod, product_path(params[:locale], product.id) %></strong>
          <%= image_tag("gwiazdki#{product.poziom}.jpg", class: 'ml-3') %>
        </h4>
        <strong><%= product.tytul_en %></strong><br>
        Level (<%= product.poziom %>)<br><br>
        <%= image_tag("gwarancja#{product.poziom}.jpg") %>
        <br>
        <br>
        <%= product.opis_krotki_en %>
      </div>

    </div>
  </div>

<% end %>



<%= paginate @products %>

app/views/products/new.html.erb
<% content_for :title do %>
  <title>Nowy produkt</title>
<% end %>

<% content_for :metatag_robots do %>
  <meta name="robots" content="noindex nofollow">
<% end %>



<h1>Nowy produkt</h1>

<br>

<%= form_with model: @product, url: products_path do |form| %>

  <%= render 'form_new_and_edit', form: form, product: @product %>

  <br>

  <%= form.submit 'Utwórz produkt', class: 'btn btn-secondary' %>

<% end %>

app/views/products/show.en.html.erb
<% content_for :title do %>
  <title><%= @product.kod %> - <%= @product.tytul_en %></title>
<% end %>

<% content_for :metatag_description do %>
  <meta name="description" content="<%= @product.kod %> - <%= @product.tytul_en %>">
<% end %>



<% if user_signed_in? && current_user.id == 1 %>

  <hr>

  <%= link_to 'Edit product', edit_product_path(params[:locale], @product.id), class: 'btn btn-secondary' %>
  <%= link_to 'Delete product', product_path(params[:locale], @product.id), method: :delete, data: { confirm: "Are you sure to DELETE the product?" }, class: 'btn btn-danger ml-5' %>

  <br>
  <br>

  <table class="table border">
    <thead>
      <tr>
        <th scope="col">Capacity</th>
        <th scope="col">Price</th>
        <th scope="col">Currency</th>
        <th scope="col">-</th>
        <th scope="col">-</th>
      </tr>
    </thead>
    <tbody>
      <% @volumes.each do |volume| %>
        <tr>
            <td><%= volume.pojemnosc %></td>
            <td><%= volume.cena %></td>
            <td><%= volume.waluta %></td>
            <td><%= link_to 'Edit', edit_product_volume_path(params[:locale], volume.product_id, volume.id), class: 'btn btn-sm btn-secondary' %></td>
            <td><%= link_to 'Delete', product_volume_path(params[:locale], volume.product_id, volume.id), method: :delete, data: { confirm: "Are you sure to DELETE capacity and price?" }, class: 'btn btn-sm btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Add capacity and price', new_product_volume_path(params[:locale], @product.id), class: 'btn btn-secondary' %>

  
  <br>
  <hr>
  <br>

<% end %>



<h4>
  <strong><%= @product.kod %></strong>
  <%= image_tag("gwiazdki#{@product.poziom}.jpg", class: 'ml-3') %>
  <%= image_tag("gwarancja#{@product.poziom}.jpg", class: 'ml-5') %>
</h4>

<strong><%= @product.tytul_en %></strong><br>
Level (<%= @product.poziom %>)<br>

<br>

<div class="container">
  <div class="row">
    
    <div class="col-12 col-md-6">
      <%= image_tag(url_for(@product.miniatura), width: '200', height: '300') %>
    </div>

    <div class="col-12 col-md-6">
      
      <% volumes_price_array = Volume.where(product_id: @product.id)
        .map { |volume| ["#{volume.pojemnosc} - #{number_to_currency(volume.cena, unit: volume.waluta + " ")}", volume.id] }
        .sort!
        .reverse!
        .keep_if { |x| x[0] =~ /.*EUR.*/ } %>

      <%= form_with(url: "/#{params[:locale]}/cart_add", method: "post") do %>
        <p>
          <br>
          Quantity:
          <%= text_field_tag(:ilosc, 1, { class: 'form-control'}) %>
          <br>
          Capacity:
          <%= select_tag(:wariant, options_for_select(volumes_price_array.to_a), { class: 'form-control'}) %>
        </p>

        <p><%= submit_tag('Add to cart', data: { "disable-with": "Adding..." }, class: 'btn btn-dark', id: 'dodaj-do-koszyka') %></p>
      <% end %>

    </div>

  </div>
</div>

<br>

Capacities: <%= volumes_only(product: @product) %>

<br>
<br>

<%= @product.opis_dlugi_en %>

<br>
<br>

<%= render 'przypomnienie' %>

app/views/products/show.html.erb
<% content_for :title do %>
  <title><%= @product.kod %> - <%= @product.tytul %></title>
<% end %>

<% content_for :metatag_description do %>
  <meta name="description" content="<%= @product.kod %> - <%= @product.tytul %>">
<% end %>



<% if user_signed_in? && current_user.id == 1 %>

  <hr>

  <%= link_to 'Edytuj produkt', edit_product_path(params[:locale], @product.id), class: 'btn btn-secondary' %>
  <%= link_to 'Usuń produkt', product_path(params[:locale], @product.id), method: :delete, data: { confirm: "Czy na pewno USUNĄĆ produkt?" }, class: 'btn btn-danger ml-5' %>

  <br>
  <br>

  <table class="table border">
    <thead>
      <tr>
        <th scope="col">Pojemność</th>
        <th scope="col">Cena</th>
        <th scope="col">Waluta</th>
        <th scope="col">-</th>
        <th scope="col">-</th>
      </tr>
    </thead>
    <tbody>
      <% @volumes.each do |volume| %>
        <tr>
            <td><%= volume.pojemnosc %></td>
            <td><%= volume.cena %></td>
            <td><%= volume.waluta %></td>
            <td><%= link_to 'Edytuj', edit_product_volume_path(params[:locale], volume.product_id, volume.id), class: 'btn btn-sm btn-secondary' %></td>
            <td><%= link_to 'Usuń', product_volume_path(params[:locale], volume.product_id, volume.id), method: :delete, data: { confirm: "Czy na pewno USUNĄĆ pojemność i cenę?" }, class: 'btn btn-sm btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Dodaj pojemność i cenę', new_product_volume_path(params[:locale], @product.id), class: 'btn btn-secondary' %>

  
  <br>
  <hr>
  <br>

<% end %>



<h4>
  <strong><%= @product.kod %></strong>
  <%= image_tag("gwiazdki#{@product.poziom}.jpg", class: 'ml-3') %>
  <%= image_tag("gwarancja#{@product.poziom}.jpg", class: 'ml-5') %>
</h4>

<strong><%= @product.tytul %></strong><br>
Poziom (<%= @product.poziom %>)<br>

<br>

<div class="container">
  <div class="row">
    
    <div class="col-12 col-md-6">
      <%= image_tag(url_for(@product.miniatura), width: '200', height: '300') %>
    </div>

    <div class="col-12 col-md-6">
      
      <% volumes_price_array = Volume.where(product_id: @product.id)
        .map { |volume| ["#{volume.pojemnosc} - #{number_to_currency(volume.cena, unit: volume.waluta + " ")}", volume.id] }
        .sort!
        .reverse!
        .keep_if { |x| x[0] =~ /.*PLN.*/ } %>

      <%= form_with(url: "/#{params[:locale]}/cart_add", method: "post") do %>
        <p>
          <br>
          Sztuk:
          <%= text_field_tag(:ilosc, 1, { class: 'form-control'}) %>
          <br>
          Pojemność:
          <%= select_tag(:wariant, options_for_select(volumes_price_array.to_a), { class: 'form-control'}) %>
        </p>

        <p><%= submit_tag('Dodaj do koszyka', data: { "disable-with": "Dodawanie..." }, class: 'btn btn-dark', id: 'dodaj-do-koszyka') %></p>
      <% end %>

    </div>

  </div>
</div>

<br>

Pojemności: <%= volumes_only(product: @product) %>

<br>
<br>

<%= @product.opis_dlugi %>

<br>
<br>

<%= render 'przypomnienie' %>