config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /pl|en/ do
    devise_for :users

    get   '/orders/prepare',  to: 'orders#prepare'
    get   '/orders/send_message', to: 'orders#prepare'
    post  '/orders/send_message', to: 'orders#send_message'

    resources :cart, only: :index
    post  '/cart_add',     to: 'cart#cart_add_to'
    post  '/cart_remove',  to: 'cart#cart_remove_from'
    get   '/cart_empty',   to: 'cart#cart_empty'

    get '/search', to: 'products#index'
    resources :products do
      resources :volumes
    end
  
    get '/kontakt', to: 'kontakt#kontakt', as: :kontakt

    scope '/aerozole' do
      get '/nasze-aerozole',    to: 'aerozole#nasze_aerozole', as: :nasze_aerozole
      get '/aerozole-w-zyciu',  to: 'aerozole#aerozole_w_zyciu', as: :aerozole_w_zyciu
      get '/proces-produkcji',  to: 'aerozole#proces_produkcji', as: :proces_produkcji
    end

    scope '/firma' do
      get '/o-nas',     to: 'firma#o_nas', as: :o_nas
      get '/gwarancja', to: 'firma#gwarancja', as: :gwarancja
      get '/ekologia',  to: 'firma#ekologia', as: :ekologia
    end

    get '/', to: "firma#o_nas"

  end

  root to: 'firma#o_nas', locale: 'pl'

end

app/views/layouts/_cookies.en.html.erb
<% if cookies[:cookies_notification] != 'closed' %>
  <div class="alert alert-dark alert-dismissible fade show" role="alert">
    This site uses cookies for the proper functioning of the store and shopping cart.
    <button type="button" class="close" id="cookies-notification-close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_cookies.html.erb
<% if cookies[:cookies_notification] != 'closed' %>
  <div class="alert alert-dark alert-dismissible fade show" role="alert">
    Ta strona używa plików cookies w celu poprawnego funkcjonowania sklepu i koszyka.
    <button type="button" class="close" id="cookies-notification-close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.en.html.erb
<div class="footer-images">
  <div>
    <%= image_tag 'stopka/swedish-technology.png', class: 'footer-image' %>
  </div>
  <div>
    <%= image_tag 'stopka/made-in-poland.png', class: 'footer-image' %>
  </div>
</div>

<div class="footer-text-1">
  <strong>Extra power, gigantic efficiency, mega savings, ultra effectiveness</strong> - these are SEX (6) levels, which are marked with six stars and have a 6-year warranty - which is a lot of everything out of six. It also specifies that only products from the SEX (6) level will satisfy your mega needs. Six in Swedish is SEX, so we have the most SEXiest sprays in the world!
</div>

<div class="footer-text-2">
  <strong>Approved and authorized for purchase/use by branches of <%= link_to_if controller.action_name == 'o_nas', image_tag('stopka/abb-small.png', width: '45px'), new_user_session_path, rel: 'noindex nofollow' %> in all countries of the world</strong>
  <br>
  <%= image_tag 'stopka/abb-big.png', width: '200px', class: 'abb-big' %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-images">
  <div>
    <%= image_tag 'stopka/swedish-technology.png', class: 'footer-image' %>
  </div>
  <div>
    <%= image_tag 'stopka/made-in-poland.png', class: 'footer-image' %>
  </div>
</div>

<div class="footer-text-1">
  <strong>Ekstra moc, giga wydajność, mega oszczędność, ultra skuteczność</strong> - to poziomy SEX (6), które oznakowane są sześcioma gwiazdkami oraz mają 6 lat gwarancji - czyli dużo wszystkiego z sześć. To też precyzuje, że tylko produkty z poziomu SEX (6) zaspokoją Twoje mega potrzeby. Sześć po szwedzku to SEX, a więc mamy najSEXowniejsze spraye na świecie!
</div>

<div class="footer-text-2">
  <strong>Zatwierdzone i dopuszczone do zakupów/użytku przez oddziały <%= link_to_if controller.action_name == 'o_nas', image_tag('stopka/abb-small.png', width: '45px'), new_user_session_path, rel: 'noindex nofollow' %> we wszystkich krajach świata</strong>
  <br>
  <%= image_tag 'stopka/abb-big.png', width: '200px', class: 'abb-big' %>
</div>

app/views/layouts/_koszyk.html.erb
<% if controller_name == 'sessions' || controller_name == 'registrations' %>
  <%= link_to "Koszyk", cart_index_path %>
<% else %>
  <%= link_to "Koszyk ( #{@koszyk.ile_w_koszyku} )", cart_index_path %>
<% end %>

app/views/layouts/_menu-mobile.html.erb
<div id="menu-center">
  <%= link_to image_tag('johansson.png', id: 'menu-image', class: 'logo-rwd'), root_path %>
</div>

<div>
  <button type="button" class="btn btn-dark mr-2" data-toggle="modal" data-target="#exampleModalScrollable">
    MENU
  </button>
</div>

app/views/layouts/_menu-right.en.html.erb
<div id="menu-right">

  <ul class="menu-ul-outer">
    
    <% if user_signed_in? && current_user.id == 1 %>
      <li class="menu-li-outer">
        Admin
        <ul class="menu-ul-inner px-0">
          <li><%= link_to 'New product', new_product_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    <% end %>

    <li class="menu-li-outer">
      Company
      <ul class="menu-ul-inner px-0">
        <li><%= link_to 'About', o_nas_path %></li>
        <li><%= link_to 'Warranty', gwarancja_path %></li>
        <li><%= link_to 'Ecology', ekologia_path %></li>
      </ul>
    </li>

    <li class="menu-li-outer">
      Aerosols
      <ul class="menu-ul-inner px-0">
        <li><%= link_to 'Our aerosols', nasze_aerozole_path %></li>
        <li><%= link_to 'Aerosols in life', aerozole_w_zyciu_path %></li>
        <li><%= link_to 'Production process', proces_produkcji_path %></li>
      </ul>
    </li>
    
    <li class="menu-li-outer"><%= link_to 'Contact', kontakt_path %></li>

  </ul>

</div>

app/views/layouts/_menu-right.html.erb
<div id="menu-right">

  <ul class="menu-ul-outer">
    
    <% if user_signed_in? && current_user.id == 1 %>
      <li class="menu-li-outer">
        Admin
        <ul class="menu-ul-inner px-0">
          <li><%= link_to 'Nowy produkt', new_product_path %></li>
          <li><%= link_to 'Wyloguj', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    <% end %>

    <li class="menu-li-outer">
      Firma
      <ul class="menu-ul-inner px-0">
        <li><%= link_to 'O nas', o_nas_path %></li>
        <li><%= link_to 'Gwarancja', gwarancja_path %></li>
        <li><%= link_to 'Ekologia', ekologia_path %></li>
      </ul>
    </li>

    <li class="menu-li-outer">
      O&nbsp;aerozolach
      <ul class="menu-ul-inner px-0">
        <li><%= link_to 'Nasze aerozole', nasze_aerozole_path %></li>
        <li><%= link_to 'Aerozole w życiu', aerozole_w_zyciu_path %></li>
        <li><%= link_to 'Proces produkcji', proces_produkcji_path %></li>
      </ul>
    </li>
    
    <li class="menu-li-outer"><%= link_to 'Kontakt', kontakt_path %></li>

  </ul>

</div>

app/views/layouts/_modal.en.html.erb
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Johansson</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
        <ul>
          <li><%= link_to 'Search product', products_path(filter: 'wszystkie') %></li>
          <li>
            <div class="koszyk-slot">
              <%= render 'layouts/koszyk' %>
            </div>
          </li>
        </ul>

        <%= render 'layouts/menu-left' %>

        <%= render 'layouts/menu-right' %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_subtitle-panel.en.html.erb
<span>
  <%= link_to image_tag('flagi/flaga1.png'), '/pl/' + lokalizacja.to_s %>
  <%= link_to image_tag('flagi/flaga2.png'), '/en/' + lokalizacja.to_s %>
  <%= image_tag('flagi/flaga3.png') %>
  <%= image_tag('flagi/flaga4.png') %>
  <%= image_tag('flagi/flaga5.png') %>
</span>

<span>Manufacturer of lubricants and technical chemistry &mdash; also in aerosols</span>

<span class="greasy">Johansson &mdash; doing good!</span>

app/views/layouts/_subtitle-panel.html.erb
<span>
  <%= link_to image_tag('flagi/flaga1.png'), '/pl/' + lokalizacja.to_s %>
  <%= link_to image_tag('flagi/flaga2.png'), '/en/' + lokalizacja.to_s %>
  <%= image_tag('flagi/flaga3.png') %>
  <%= image_tag('flagi/flaga4.png') %>
  <%= image_tag('flagi/flaga5.png') %>
</span>

<span>Producent środków smarujących i chemii technicznej &mdash; również w aerozolach</span>

<span class="greasy">Johansson &mdash; robi dobrze!</span>

app/views/layouts/application_cart.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :title %>

    <%= yield :metatag_description if :metatag_description %>

    <%= yield :metatag_robots if :metatag_robots %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Russo+One&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">
      <div class="row">
        <div class="col-12 px-0">

          <%= render 'layouts/modal' %>
          
          <div class="menu">
            <%= render 'layouts/menu-left' %>

            <div id="menu-center">
              <%= link_to image_tag('johansson.png', id: 'menu-image'), o_nas_path %>
            </div>

            <%= render 'layouts/menu-right' %>
          </div>

          <div class="menu-mobile">
            <%= render 'layouts/menu-mobile' %>
          </div>

          <div class="subtitle-panel">
            <%= render 'layouts/subtitle-panel' %>
          </div>

        </div>
      </div>
    </div>
   
    <div class="container pt-5">
      <div class="row">
        <div class="col-12 offset-0"> 

          <%= render 'layouts/flash' %>

          <%= render 'layouts/cookies' %>

          <%= yield %>

        </div>
      </div>

      <div class="row row-footer mt-5">
        <div class="col-12 offset-0"> 
          <%= render 'layouts/footer' %>
        </div>  
      </div>
    </div>

  </body>
</html>